[[block]]
alias = "/"
block = "disk_space"
info_type = "available"
path = "/"
unit = "GB"

[[block]]
block = "memory"
clickable = false
display_type = "memory"
format_mem = "{mem_used_percents}"
interval = 4

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 2

[[block]]
block = "load"
format = "{1m} {5m}"
interval = 4

[[block]]
block = "temperature"
chip = "k10temp-pci-*"
collapsed = false
format = "{max}"
interval = 4

[[block]]
block = "temperature"
chip = "amdgpu-pci-*"
collapsed = false
format = "{max}"
interval = 4

[[block]]
block = "net"
device = "eno1"
interval = 2

[[block]]
block = "sound"
step_width = 6

[[block]]
block = "time"
format = "%d %b %l:%M %p"
interval = 60

[icons]
[icons.overrides]
cogs = " "
cpu = ""
memory_mem = ""
net_down = ""
net_up = ""
net_wired = ""
net_wireless = ""
thermometer = " "
time = " "
volume_empty = " "
volume_full = " "
volume_half = "奔 "
volume_muted = "ﱝ "

[theme]
name = "modern"

[theme.overrides]
critical_bg = "#D08770"
critical_fg = "#2E3440"
good_bg = "#2E3440"
good_fg = "#E5E9F0"
idle_bg = "#2E3440"
idle_fg = "#E5E9F0"
info_bg = "#2E3440"
info_fg = "#E5E9F0"
warning_bg = "#5E81AC"
warning_fg = "#2E3440"
